POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV2b2x2ZSIsImlkIjoiNjJiMjc2OWFmN2Y1ZDdmZDAwZDk4NWEyIiwiaWF0IjoxNjU1OTM3MzM4LCJleHAiOjE2NTU5NDA5Mzh9.Ji4vYME2mj18OhKVPvIP4Z_raoml0-RLBco0-l-bPjQ

{
  "title": "user test #2",
  "author": "loki",
  "url": "google.com",
  "likes": 0
}